modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
modId="examplemod" 
version="${file.jarVersion}"
displayName="Example Mod"
# The description text for the mod (multi line!) (#mandatory)
description='''
This is an Example Mod written for a Forge PR. Check the folder name for the PR number!'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
